language: python
python:
- '3.6'
before_install:
- export DJANGO_EXCHANGER_DEBUG=False
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: mmBHIOBkY9svQi/tb4D2589DXAqSvFXZxDOpnsOgkCN34njMMnBgn/oxNAtRvTn4DCxefbMY/2XshsfuVHZUTw2n4YVKmSRGh5G4n0X0FV4dtsK3PQ1OusXTecdUones/O3zXiYVO/L2hKWuAy66ueOMTwVviFIuwLaQFEMdAKmD0bgc4967tEX9+9OvUictYPFRD3zR1zDjxP2JMK9wCwaoVZGX8bFuO7qLQtPO6LwxWcf4NXk5oG2l40xWeiS9KUVm1t2r44u44FDKAfVOxF8pnLzILvPQ5W8g17vdHUtO9rwkA77KP7VX8Mk5eoocDA2Yu+QOfnr480lKQAzLDXoKhoUMoRP17O9FePb0s6TXalYlsna9wOL6Rp0F+PJEhrtaNGnxDn1jcZzfqBFgP+TaaF1U+UA76xQb/A+vxsJCudNvDVOYTs03tI6NR7PSFn/9bil9feX+f4v2jYPu5HBjaNzv7DZyk222UnaUPIYyodA1KrcZ4/TPTz4cpIR70+nX/9NEtX/7CKeiJN1Hh4yW84chm9JoBI5HcOiYLibtcDBQqXYbSdouiaFDkfEAYYh30cmAHbPq0xhc3dRdpTsyVM51AQSps5MnTmPQItdBehGrFxBTGhLPmdlSC3Rs7nLb/opFESR/JL5VG8veai1v5Nr5TsKjrQbA80jLTS0=
    app: exchanger-app